apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config #
  namespace: kube-system
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      format json
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        namespace ${record["kubernetes"]["namespace_name"]}
      </record>
    </filter>


    # <match pattern>
    #   @type http

    #   endpoint https://172.20.10.4:4000
    #   open_timeout 2

    #   <format>
    #   @type json
    #   </format>
    #   <buffer>
    #     flush_interval 10s
    #   </buffer>
    # </match>

    <match pattern>
      @type tcp
      host 172.20.10.4
      port 400
      format json
    </match>
