apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush             5
        Daemon           Off
        Log_Level        info
        Parsers_File     parsers.conf
        HTTP_Server      On
        HTTP_Listen      0.0.0.0
        HTTP_Port        2020

    [INPUT]
        Name             tail
        Tag              apt_logs
        Path             /var/log/apt/history.log
        Parser           apt_parser
        DB               /var/fluent-bit/state.db
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
        Refresh_Interval 5
        Read_from_Head   True

    # Add cluster metadata to logs
    [FILTER]
        Name               record_modifier
        Match              apt_logs
        Record             cluster_name minikube

    [OUTPUT]
        Name              websocket
        Match             apt_logs
        Host              host.docker.internal
        Port              4000
        Format            json
        URI               /
        Retry_Limit       False
        Net.Keepalive     On
        Net.Keepalive_Idle_Timeout 30
        tls.verify        Off

  parsers.conf: |
    [PARSER]
        Name        apt_parser
        Format      regex
        Regex       ^Start-Date: (?<date>[^ ]+) .* Commandline: (?<command>.*)
        Time_Key    date
        Time_Format %Y-%m-%d
        Time_Keep   On
