#rbac.yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ws-server-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-logs-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-logs-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: ws-server-sa
    namespace: default
roleRef:
  kind: Role
  name: pod-logs-reader
  apiGroup: rbac.authorization.k8s.io

---
#websocket-server.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-server
  template:
    metadata:
      labels:
        app: ws-server
    spec:
      serviceAccountName: ws-server-sa  # Give pod necessary permissions
      containers:
        - name: ws-server
          image: mjanith/ws-server:1.3
          ports:
            - containerPort: 9000
apiVersion: v1
kind: Service
metadata:
  name: ws-service
spec:
  selector:
    app: ws-server
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort
